name: Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth pandas

      - name: Print secrets presence
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: |
          if [ -z "${SPREADSHEET_ID}" ]; then echo "SPREADSHEET_ID=⛔"; else echo "SPREADSHEET_ID=✅"; fi
          if [ -z "${GOOGLE_SHEETS_JSON}" ]; then echo "GOOGLE_SHEETS_JSON=⛔"; else echo "GOOGLE_SHEETS_JSON=✅"; fi

      - name: Try read first row
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: |
          python - <<'PY'
          import os, json
          import gspread
          from google.oauth2.service_account import Credentials

          sid = os.getenv("SPREADSHEET_ID")
          js = os.getenv("GOOGLE_SHEETS_JSON")
          if not sid or not js:
              print("⛔ Falta secreto")
              raise SystemExit(0)
          creds = Credentials.from_service_account_info(json.loads(js), scopes=["https://www.googleapis.com/auth/spreadsheets"])
          gc = gspread.authorize(creds)
          ws = gc.open_by_key(sid).sheet1
          vals = ws.get_all_values()
          print("✅ Filas leídas:", len(vals))
          print("👀 Primera fila:", vals[0] if vals else "vacío")
          PY
