name: Debug Bot

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies (debug)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Debug Script
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: |
          python - <<'EOF'
          import sys
          import pandas, numpy, yfinance, gspread
          print("✅ Debug: librerías importadas correctamente")
          from bot import process_signal
          row = process_signal("DKNG","Buy",45.3)
          print("✅ Señal de prueba guardada:", row)
          EOF
