name: Debug Bot

on:
  workflow_dispatch:   # Solo manual para no spamear

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot in debug mode
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
          ALERT_DKNG: ${{ secrets.ALERT_DKNG }}
          ALERT_MICROS: ${{ secrets.ALERT_MICROS }}
          ALERT_DEFAULT: ${{ secrets.ALERT_DEFAULT }}
        run: |
          echo "🚀 Running bot in DEBUG mode..."
          python bot.py
