name: Update & Notify Results

on:
  schedule:
    - cron: "*/5 * * * *"   # ⏱️ Ejecutar cada 5 minutos
  workflow_dispatch:         # Permitir ejecución manual desde GitHub

jobs:
  update-results:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ⚙️ Run update_results.py
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
        run: |
          echo "🚀 Ejecutando actualización automática de mercado y señales..."
          python update_results.py
