name: Update Trade Results

on:
  schedule:
    # 🕒 Cada 5 minutos — sincronizado con run-bot.yml
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run results updater
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
        run: |
          echo "📈 Verificando confirmaciones y resultados..."
          python update_results.py

      - name: Cleanup old logs (7-day retention)
        run: |
          echo "🧹 Limpiando logs antiguos"
          find . -name "*.log" -type f -mtime +7 -delete
